name: pescadorapp
description: A new Flutter project.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  cloud_firestore: ^2.4.0
  firebase_core: ^1.1.0
  font_awesome_flutter: ^10.1.0
  flutter_calendar_carousel: ^2.1.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/image/

  fonts:
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow-Regular.ttf